# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  [workflow_dispatch, pull_request, push]